

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healosbench
    ports:
      - "5433:5432" # Mapping to 5433 to avoid conflicts with default local Postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
